services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:29093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  generador_respuestas:
    build:
      context: .
      dockerfile: Dockerfile.respuestas
    container_name: generador_respuestas
    ports:
      - "8001:8001"
    environment:
      - RUTA_CSV=967_buildings.csv
      - SIMULAR_FALLOS=false
      - PROBABILIDAD_FALLO=0.0
      - LATENCIA_ARTIFICIAL_MS=0
    volumes:
      - ./967_buildings.csv:/app/967_buildings.csv:ro

  cache:
    build:
      context: .
      dockerfile: Dockerfile.cache
    container_name: cache
    ports:
      - "8000:8000"
    environment:
      - HOST_REDIS=redis
      - PUERTO_REDIS=6379
      - DB_REDIS=0
      - TTL_SEGUNDOS=120
      - URL_GENERADOR_RESPUESTAS=http://generador_respuestas:8001/resolver
      - URL_CACHE=http://cache:8000/consulta
      - INTERVALO_SEGUNDOS=10
      - DISTRIBUCION=uniforme
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - TOPIC_CONSULTAS=consultas
      - TOPIC_RESPUESTAS=respuestas
      - TOPIC_RETRY=consultas_retry
      - TOPIC_DLQ=consultas_dlq
    depends_on:
      - redis
      - kafka
      - generador_respuestas
    volumes:
      - ./metricas_output:/app/metricas_output

  consumer_respuestas:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    environment:
      - HOST_REDIS=redis
      - PUERTO_REDIS=6379
      - DB_REDIS=0
      - TTL_SEGUNDOS=120
      - TTL_ESTADO_CONSULTA_SEGUNDOS=600
      - RUTA_CSV=967_buildings.csv
      - SIMULAR_FALLOS=false
      - PROBABILIDAD_FALLO=0.0
      - LATENCIA_ARTIFICIAL_MS=0
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - TOPIC_CONSULTAS=consultas
      - TOPIC_RESPUESTAS=respuestas
      - TOPIC_RETRY=consultas_retry
      - TOPIC_DLQ=consultas_dlq
      - KAFKA_GROUP_ID=consumer-respuestas
      - MAX_INTENTOS=3
      - ESCENARIO=kafka
      - NUM_CONSUMIDORES=1
    depends_on:
      - redis
      - kafka
    volumes:
      - ./967_buildings.csv:/app/967_buildings.csv:ro
      - ./metricas_output:/app/metricas_output

  generador_trafico:
    build:
      context: .
      dockerfile: Dockerfile.trafico
    container_name: generador_trafico
    environment:
      - URL_CACHE=http://cache:8000/consulta
      - INTERVALO_SEGUNDOS=10
      - DISTRIBUCION=uniforme
      - MODO_TRAFICO=normal
      - CONSULTAS_POR_SEGUNDO=0
      - SPIKE_CONSULTAS_POR_SEGUNDO=10
      - DURACION_SPIKE_SEGUNDOS=30
      - DURACION_TOTAL_SEGUNDOS=0
      - CONCURRENCIA=10
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - TOPIC_CONSULTAS=consultas
    depends_on:
      - cache
