FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY generador_respuestas.py .
COPY 967_buildings.csv .

EXPOSE 8001

CMD ["uvicorn", "generador_respuestas:app", "--host", "0.0.0.0", "--port", "8001"]