FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY cache.py .
COPY conexion_redis.py .
COPY metricas.py .

EXPOSE 8000

CMD ["uvicorn", "cache:app", "--host", "0.0.0.0", "--port", "8000"]