FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY consumer_respuestas.py .
COPY generador_respuestas.py .
COPY metricas.py .

CMD ["python", "consumer_respuestas.py"]
